// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6QDhNZVYk1wqrh7867eY5G5blUjfif90',
    appId: '1:492151769279:web:895769d8850f36e8d4de0a',
    messagingSenderId: '492151769279',
    projectId: 'dukan-baladna1',
    authDomain: 'dukan-baladna1.firebaseapp.com',
    storageBucket: 'dukan-baladna1.firebasestorage.app',
    measurementId: 'G-WNQXQ72XFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1znSzHiUlBnJTe9PmOI-ozpZI7mApMDQ',
    appId: '1:492151769279:android:947c8c7b5cb7bc76d4de0a',
    messagingSenderId: '492151769279',
    projectId: 'dukan-baladna1',
    storageBucket: 'dukan-baladna1.firebasestorage.app',
  );
}
